<?php

namespace Database\Seeders\Customer;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerTableSeeder extends Seeder
{
    /**
     * Seed customer, customerTelephones, and customerPets.
     * Reference IDs used:
     *   titleCustomerId : 2 = Mrs, 5 = Mr
     *   customerGroupId : 2 = Google Data 2, 4 = Maximum Pass, 6 = VIP
     *   locationId      : 1-15 (RPC branches)
     *   occupationId    : 3 = Wiraswasta, 5 = Content Creator, 6 = PNS
     *   petCategoryId   : 1 = Ular, 2 = Anjing, 3 = Kucing, 4 = Burung, 6 = Hamster
     *   typeId          : 1 = KTP, 2 = SIM, 3 = Passport
     */
    public function run(): void
    {
        // ── 1. CUSTOMERS ─────────────────────────────────────────────────────────
        $customers = [
            [
                'id'                  => 101,
                'memberNo'            => 'MBR-2024-001',
                'firstName'           => 'Budi',
                'middleName'          => null,
                'lastName'            => 'Santoso',
                'nickName'            => 'Budi',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 6,
                'locationId'          => 1,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-01-10',
                'typeId'              => 1,
                'numberId'            => '3175012501900001',
                'occupationId'        => 3,
                'birthDate'           => '1990-01-25',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-01-10 08:00:00',
                'updated_at'          => '2024-01-10 08:00:00',
            ],
            [
                'id'                  => 102,
                'memberNo'            => 'MBR-2024-002',
                'firstName'           => 'Siti',
                'middleName'          => null,
                'lastName'            => 'Rahayu',
                'nickName'            => 'Siti',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 4,
                'locationId'          => 2,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-01-15',
                'typeId'              => 1,
                'numberId'            => '3175015501920002',
                'occupationId'        => 6,
                'birthDate'           => '1992-05-15',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 0,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-01-15 09:00:00',
                'updated_at'          => '2024-01-15 09:00:00',
            ],
            [
                'id'                  => 103,
                'memberNo'            => 'MBR-2024-003',
                'firstName'           => 'Andi',
                'middleName'          => 'Kurnia',
                'lastName'            => 'Pratama',
                'nickName'            => 'Andi',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 2,
                'locationId'          => 3,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-02-01',
                'typeId'              => 2,
                'numberId'            => 'B123456789',
                'occupationId'        => 5,
                'birthDate'           => '1988-11-03',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 0,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-02-01 10:00:00',
                'updated_at'          => '2024-02-01 10:00:00',
            ],
            [
                'id'                  => 104,
                'memberNo'            => 'MBR-2024-004',
                'firstName'           => 'Dewi',
                'middleName'          => null,
                'lastName'            => 'Lestari',
                'nickName'            => 'Dewi',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 6,
                'locationId'          => 4,
                'notes'               => 'Pelanggan setia sejak 2023',
                'colorType'           => null,
                'joinDate'            => '2024-02-10',
                'typeId'              => 1,
                'numberId'            => '3175021002940003',
                'occupationId'        => 3,
                'birthDate'           => '1994-10-02',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-02-10 11:00:00',
                'updated_at'          => '2024-02-10 11:00:00',
            ],
            [
                'id'                  => 105,
                'memberNo'            => 'MBR-2024-005',
                'firstName'           => 'Reza',
                'middleName'          => null,
                'lastName'            => 'Firmansyah',
                'nickName'            => 'Reza',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 2,
                'locationId'          => 5,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-03-05',
                'typeId'              => 1,
                'numberId'            => '3175010503870004',
                'occupationId'        => 6,
                'birthDate'           => '1987-03-05',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 0,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-03-05 08:30:00',
                'updated_at'          => '2024-03-05 08:30:00',
            ],
            [
                'id'                  => 106,
                'memberNo'            => 'MBR-2024-006',
                'firstName'           => 'Nurul',
                'middleName'          => null,
                'lastName'            => 'Hidayah',
                'nickName'            => 'Nurul',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 4,
                'locationId'          => 6,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-03-12',
                'typeId'              => 1,
                'numberId'            => '3175021203960005',
                'occupationId'        => 5,
                'birthDate'           => '1996-03-12',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 0,
                'isReminderPayment'   => 0,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-03-12 09:15:00',
                'updated_at'          => '2024-03-12 09:15:00',
            ],
            [
                'id'                  => 107,
                'memberNo'            => 'MBR-2024-007',
                'firstName'           => 'Hendra',
                'middleName'          => 'Putra',
                'lastName'            => 'Wijaya',
                'nickName'            => 'Hendra',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 6,
                'locationId'          => 7,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-04-02',
                'typeId'              => 2,
                'numberId'            => 'C987654321',
                'occupationId'        => 3,
                'birthDate'           => '1985-07-20',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-04-02 10:00:00',
                'updated_at'          => '2024-04-02 10:00:00',
            ],
            [
                'id'                  => 108,
                'memberNo'            => 'MBR-2024-008',
                'firstName'           => 'Maya',
                'middleName'          => null,
                'lastName'            => 'Anggraeni',
                'nickName'            => 'Maya',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 2,
                'locationId'          => 8,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-04-15',
                'typeId'              => 1,
                'numberId'            => '3175021504980006',
                'occupationId'        => 6,
                'birthDate'           => '1998-04-15',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-04-15 11:30:00',
                'updated_at'          => '2024-04-15 11:30:00',
            ],
            [
                'id'                  => 109,
                'memberNo'            => 'MBR-2024-009',
                'firstName'           => 'Doni',
                'middleName'          => null,
                'lastName'            => 'Setiawan',
                'nickName'            => 'Doni',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 4,
                'locationId'          => 9,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-05-01',
                'typeId'              => 1,
                'numberId'            => '3175010105910007',
                'occupationId'        => 5,
                'birthDate'           => '1991-05-01',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 0,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-05-01 08:00:00',
                'updated_at'          => '2024-05-01 08:00:00',
            ],
            [
                'id'                  => 110,
                'memberNo'            => 'MBR-2024-010',
                'firstName'           => 'Rizky',
                'middleName'          => null,
                'lastName'            => 'Amalia',
                'nickName'            => 'Rizky',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 6,
                'locationId'          => 10,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-05-20',
                'typeId'              => 1,
                'numberId'            => '3175022005930008',
                'occupationId'        => 3,
                'birthDate'           => '1993-05-20',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 0,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-05-20 09:00:00',
                'updated_at'          => '2024-05-20 09:00:00',
            ],
            [
                'id'                  => 111,
                'memberNo'            => 'MBR-2024-011',
                'firstName'           => 'Fajar',
                'middleName'          => null,
                'lastName'            => 'Nugroho',
                'nickName'            => 'Fajar',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 2,
                'locationId'          => 11,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-06-03',
                'typeId'              => 1,
                'numberId'            => '3175010306890009',
                'occupationId'        => 6,
                'birthDate'           => '1989-06-03',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-06-03 10:00:00',
                'updated_at'          => '2024-06-03 10:00:00',
            ],
            [
                'id'                  => 112,
                'memberNo'            => 'MBR-2024-012',
                'firstName'           => 'Indah',
                'middleName'          => 'Putri',
                'lastName'            => 'Permata',
                'nickName'            => 'Indah',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 4,
                'locationId'          => 12,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-06-18',
                'typeId'              => 1,
                'numberId'            => '3175021806950010',
                'occupationId'        => 5,
                'birthDate'           => '1995-06-18',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 0,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-06-18 11:00:00',
                'updated_at'          => '2024-06-18 11:00:00',
            ],
            [
                'id'                  => 113,
                'memberNo'            => 'MBR-2024-013',
                'firstName'           => 'Wahyu',
                'middleName'          => null,
                'lastName'            => 'Kusuma',
                'nickName'            => 'Wahyu',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 6,
                'locationId'          => 13,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-07-01',
                'typeId'              => 2,
                'numberId'            => 'D112233445',
                'occupationId'        => 3,
                'birthDate'           => '1986-09-14',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 0,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-07-01 08:30:00',
                'updated_at'          => '2024-07-01 08:30:00',
            ],
            [
                'id'                  => 114,
                'memberNo'            => 'MBR-2024-014',
                'firstName'           => 'Yuni',
                'middleName'          => null,
                'lastName'            => 'Astuti',
                'nickName'            => 'Yuni',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 2,
                'locationId'          => 14,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-07-10',
                'typeId'              => 1,
                'numberId'            => '3175021007970011',
                'occupationId'        => 6,
                'birthDate'           => '1997-07-10',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-07-10 09:00:00',
                'updated_at'          => '2024-07-10 09:00:00',
            ],
            [
                'id'                  => 115,
                'memberNo'            => 'MBR-2024-015',
                'firstName'           => 'Teguh',
                'middleName'          => null,
                'lastName'            => 'Wibowo',
                'nickName'            => 'Teguh',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 4,
                'locationId'          => 15,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-07-22',
                'typeId'              => 1,
                'numberId'            => '3175012207840012',
                'occupationId'        => 5,
                'birthDate'           => '1984-07-22',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 0,
                'isReminderPayment'   => 0,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-07-22 10:30:00',
                'updated_at'          => '2024-07-22 10:30:00',
            ],
            [
                'id'                  => 116,
                'memberNo'            => 'MBR-2024-016',
                'firstName'           => 'Ayu',
                'middleName'          => null,
                'lastName'            => 'Wulandari',
                'nickName'            => 'Ayu',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 6,
                'locationId'          => 1,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-08-05',
                'typeId'              => 1,
                'numberId'            => '3175020508930013',
                'occupationId'        => 3,
                'birthDate'           => '1993-08-05',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-08-05 08:00:00',
                'updated_at'          => '2024-08-05 08:00:00',
            ],
            [
                'id'                  => 117,
                'memberNo'            => 'MBR-2024-017',
                'firstName'           => 'Dimas',
                'middleName'          => 'Ari',
                'lastName'            => 'Saputra',
                'nickName'            => 'Dimas',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 2,
                'locationId'          => 2,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-08-20',
                'typeId'              => 1,
                'numberId'            => '3175012008920014',
                'occupationId'        => 6,
                'birthDate'           => '1992-08-20',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 0,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-08-20 09:30:00',
                'updated_at'          => '2024-08-20 09:30:00',
            ],
            [
                'id'                  => 118,
                'memberNo'            => 'MBR-2024-018',
                'firstName'           => 'Fitri',
                'middleName'          => null,
                'lastName'            => 'Handayani',
                'nickName'            => 'Fitri',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 4,
                'locationId'          => 3,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-09-01',
                'typeId'              => 1,
                'numberId'            => '3175020109960015',
                'occupationId'        => 5,
                'birthDate'           => '1996-09-01',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 0,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-09-01 10:00:00',
                'updated_at'          => '2024-09-01 10:00:00',
            ],
            [
                'id'                  => 119,
                'memberNo'            => 'MBR-2024-019',
                'firstName'           => 'Bagas',
                'middleName'          => null,
                'lastName'            => 'Prasetyo',
                'nickName'            => 'Bagas',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 6,
                'locationId'          => 4,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-09-15',
                'typeId'              => 2,
                'numberId'            => 'E556677889',
                'occupationId'        => 3,
                'birthDate'           => '1990-04-11',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-09-15 11:00:00',
                'updated_at'          => '2024-09-15 11:00:00',
            ],
            [
                'id'                  => 120,
                'memberNo'            => 'MBR-2024-020',
                'firstName'           => 'Laila',
                'middleName'          => null,
                'lastName'            => 'Safitri',
                'nickName'            => 'Laila',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 2,
                'locationId'          => 5,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-10-01',
                'typeId'              => 1,
                'numberId'            => '3175020110950016',
                'occupationId'        => 6,
                'birthDate'           => '1995-10-01',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 0,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-10-01 08:00:00',
                'updated_at'          => '2024-10-01 08:00:00',
            ],
            [
                'id'                  => 121,
                'memberNo'            => 'MBR-2024-021',
                'firstName'           => 'Arif',
                'middleName'          => null,
                'lastName'            => 'Budiman',
                'nickName'            => 'Arif',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 4,
                'locationId'          => 6,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-10-10',
                'typeId'              => 1,
                'numberId'            => '3175011010830017',
                'occupationId'        => 5,
                'birthDate'           => '1983-10-10',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 0,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-10-10 09:00:00',
                'updated_at'          => '2024-10-10 09:00:00',
            ],
            [
                'id'                  => 122,
                'memberNo'            => 'MBR-2024-022',
                'firstName'           => 'Rini',
                'middleName'          => null,
                'lastName'            => 'Marlina',
                'nickName'            => 'Rini',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 6,
                'locationId'          => 7,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-10-25',
                'typeId'              => 1,
                'numberId'            => '3175022510990018',
                'occupationId'        => 3,
                'birthDate'           => '1999-10-25',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-10-25 10:30:00',
                'updated_at'          => '2024-10-25 10:30:00',
            ],
            [
                'id'                  => 123,
                'memberNo'            => 'MBR-2024-023',
                'firstName'           => 'Surya',
                'middleName'          => 'Eka',
                'lastName'            => 'Purnama',
                'nickName'            => 'Surya',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 2,
                'locationId'          => 8,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-11-03',
                'typeId'              => 1,
                'numberId'            => '3175010311870019',
                'occupationId'        => 6,
                'birthDate'           => '1987-11-03',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 0,
                'isReminderPayment'   => 0,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-11-03 08:00:00',
                'updated_at'          => '2024-11-03 08:00:00',
            ],
            [
                'id'                  => 124,
                'memberNo'            => 'MBR-2024-024',
                'firstName'           => 'Tari',
                'middleName'          => null,
                'lastName'            => 'Ramadhani',
                'nickName'            => 'Tari',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 4,
                'locationId'          => 9,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-11-15',
                'typeId'              => 1,
                'numberId'            => '3175021511940020',
                'occupationId'        => 5,
                'birthDate'           => '1994-11-15',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-11-15 09:00:00',
                'updated_at'          => '2024-11-15 09:00:00',
            ],
            [
                'id'                  => 125,
                'memberNo'            => 'MBR-2024-025',
                'firstName'           => 'Iwan',
                'middleName'          => null,
                'lastName'            => 'Kurniawan',
                'nickName'            => 'Iwan',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 6,
                'locationId'          => 10,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-12-01',
                'typeId'              => 2,
                'numberId'            => 'F223344556',
                'occupationId'        => 3,
                'birthDate'           => '1982-12-01',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 0,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-12-01 10:00:00',
                'updated_at'          => '2024-12-01 10:00:00',
            ],
            [
                'id'                  => 126,
                'memberNo'            => 'MBR-2024-026',
                'firstName'           => 'Nadia',
                'middleName'          => null,
                'lastName'            => 'Putri',
                'nickName'            => 'Nadia',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 2,
                'locationId'          => 11,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2024-12-10',
                'typeId'              => 1,
                'numberId'            => '3175021012970021',
                'occupationId'        => 6,
                'birthDate'           => '1997-12-10',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 0,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2024-12-10 11:00:00',
                'updated_at'          => '2024-12-10 11:00:00',
            ],
            [
                'id'                  => 127,
                'memberNo'            => 'MBR-2025-027',
                'firstName'           => 'Gilang',
                'middleName'          => null,
                'lastName'            => 'Ramadan',
                'nickName'            => 'Gilang',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 4,
                'locationId'          => 12,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2025-01-05',
                'typeId'              => 1,
                'numberId'            => '3175010501910022',
                'occupationId'        => 5,
                'birthDate'           => '1991-01-05',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2025-01-05 08:00:00',
                'updated_at'          => '2025-01-05 08:00:00',
            ],
            [
                'id'                  => 128,
                'memberNo'            => 'MBR-2025-028',
                'firstName'           => 'Sari',
                'middleName'          => 'Indra',
                'lastName'            => 'Dewanti',
                'nickName'            => 'Sari',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 6,
                'locationId'          => 13,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2025-01-20',
                'typeId'              => 1,
                'numberId'            => '3175022001000023',
                'occupationId'        => 3,
                'birthDate'           => '2000-01-20',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 0,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2025-01-20 09:30:00',
                'updated_at'          => '2025-01-20 09:30:00',
            ],
            [
                'id'                  => 129,
                'memberNo'            => 'MBR-2025-029',
                'firstName'           => 'Eko',
                'middleName'          => null,
                'lastName'            => 'Prabowo',
                'nickName'            => 'Eko',
                'gender'              => 'L',
                'titleCustomerId'     => 5,
                'customerGroupId'     => 2,
                'locationId'          => 14,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2025-02-10',
                'typeId'              => 1,
                'numberId'            => '3175011002880024',
                'occupationId'        => 6,
                'birthDate'           => '1988-02-10',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 0,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2025-02-10 10:00:00',
                'updated_at'          => '2025-02-10 10:00:00',
            ],
            [
                'id'                  => 130,
                'memberNo'            => 'MBR-2025-030',
                'firstName'           => 'Mega',
                'middleName'          => null,
                'lastName'            => 'Suksma',
                'nickName'            => 'Mega',
                'gender'              => 'P',
                'titleCustomerId'     => 2,
                'customerGroupId'     => 4,
                'locationId'          => 15,
                'notes'               => null,
                'colorType'           => null,
                'joinDate'            => '2025-03-01',
                'typeId'              => 1,
                'numberId'            => '3175020103010025',
                'occupationId'        => 5,
                'birthDate'           => '2001-03-01',
                'referenceCustomerId' => null,
                'isReminderBooking'   => 1,
                'isReminderPayment'   => 1,
                'isDeleted'           => 0,
                'createdBy'           => '1',
                'userUpdateId'        => 0,
                'created_at'          => '2025-03-01 08:00:00',
                'updated_at'          => '2025-03-01 08:00:00',
            ],
        ];

        DB::table('customer')->insert($customers);

        // ── 2. CUSTOMER TELEPHONES ────────────────────────────────────────────────
        $telephones = [
            ['customerId' => 101, 'phoneNumber' => '081234567801', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 102, 'phoneNumber' => '081234567802', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 103, 'phoneNumber' => '081234567803', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 104, 'phoneNumber' => '081234567804', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 105, 'phoneNumber' => '081234567805', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 106, 'phoneNumber' => '081234567806', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 107, 'phoneNumber' => '081234567807', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 108, 'phoneNumber' => '081234567808', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 109, 'phoneNumber' => '081234567809', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 110, 'phoneNumber' => '081234567810', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 111, 'phoneNumber' => '081234567811', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 112, 'phoneNumber' => '081234567812', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 113, 'phoneNumber' => '081234567813', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 114, 'phoneNumber' => '081234567814', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 115, 'phoneNumber' => '081234567815', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 116, 'phoneNumber' => '081234567816', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 117, 'phoneNumber' => '081234567817', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 118, 'phoneNumber' => '081234567818', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 119, 'phoneNumber' => '081234567819', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 120, 'phoneNumber' => '081234567820', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 121, 'phoneNumber' => '081234567821', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 122, 'phoneNumber' => '081234567822', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 123, 'phoneNumber' => '081234567823', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 124, 'phoneNumber' => '081234567824', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 125, 'phoneNumber' => '081234567825', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 126, 'phoneNumber' => '081234567826', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 127, 'phoneNumber' => '081234567827', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 128, 'phoneNumber' => '081234567828', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 129, 'phoneNumber' => '081234567829', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 130, 'phoneNumber' => '081234567830', 'type' => 'mobile', 'usage' => 'personal', 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('customerTelephones')->insert($telephones);

        // ── 3. CUSTOMER PETS ──────────────────────────────────────────────────────
        // petCategoryId: 2=Anjing, 3=Kucing, 4=Burung, 6=Hamster
        $pets = [
            // petCategoryId: 2=Anjing, 3=Kucing, 4=Burung, 6=Hamster
            ['customerId' => 101, 'petName' => 'Max',     'petCategoryId' => 2, 'races' => 'Golden Retriever', 'condition' => 'Sehat', 'color' => 'Kuning Keemasan', 'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 6, 'petYear' => 3, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 102, 'petName' => 'Mimi',    'petCategoryId' => 3, 'races' => 'Persian',          'condition' => 'Sehat', 'color' => 'Putih',            'petGender' => 'B', 'isSteril' => 1, 'petMonth' => 3, 'petYear' => 2, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 103, 'petName' => 'Rocky',   'petCategoryId' => 2, 'races' => 'Husky',            'condition' => 'Sehat', 'color' => 'Abu-abu Putih',    'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 0, 'petYear' => 4, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 104, 'petName' => 'Luna',    'petCategoryId' => 3, 'races' => 'British Shorthair','condition' => 'Sehat', 'color' => 'Abu-abu',          'petGender' => 'B', 'isSteril' => 1, 'petMonth' => 9, 'petYear' => 1, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 105, 'petName' => 'Bonie',   'petCategoryId' => 2, 'races' => 'Pomeranian',       'condition' => 'Sehat', 'color' => 'Putih',            'petGender' => 'B', 'isSteril' => 0, 'petMonth' => 4, 'petYear' => 2, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 106, 'petName' => 'Coco',    'petCategoryId' => 3, 'races' => 'Maine Coon',       'condition' => 'Sehat', 'color' => 'Cokelat Belang',   'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 0, 'petYear' => 3, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 107, 'petName' => 'Buddy',   'petCategoryId' => 2, 'races' => 'Labrador',         'condition' => 'Sehat', 'color' => 'Hitam',            'petGender' => 'J', 'isSteril' => 1, 'petMonth' => 2, 'petYear' => 5, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 108, 'petName' => 'Nala',    'petCategoryId' => 3, 'races' => 'Anggora',          'condition' => 'Sehat', 'color' => 'Oranye',           'petGender' => 'B', 'isSteril' => 0, 'petMonth' => 7, 'petYear' => 2, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 109, 'petName' => 'Charlie', 'petCategoryId' => 2, 'races' => 'Beagle',           'condition' => 'Sehat', 'color' => 'Cokelat Putih',    'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 0, 'petYear' => 3, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 110, 'petName' => 'Bella',   'petCategoryId' => 3, 'races' => 'Scottish Fold',    'condition' => 'Sehat', 'color' => 'Kuning Belang',    'petGender' => 'B', 'isSteril' => 1, 'petMonth' => 5, 'petYear' => 1, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 111, 'petName' => 'Kiko',    'petCategoryId' => 4, 'races' => 'Lovebird',         'condition' => 'Sehat', 'color' => 'Hijau Kuning',     'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 8, 'petYear' => 1, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 112, 'petName' => 'Mochi',   'petCategoryId' => 3, 'races' => 'Ragdoll',          'condition' => 'Sehat', 'color' => 'Putih Biru',       'petGender' => 'B', 'isSteril' => 1, 'petMonth' => 0, 'petYear' => 4, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 113, 'petName' => 'Rex',     'petCategoryId' => 2, 'races' => 'German Shepherd',  'condition' => 'Sehat', 'color' => 'Hitam Cokelat',    'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 3, 'petYear' => 6, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 114, 'petName' => 'Kiki',    'petCategoryId' => 6, 'races' => 'Campbell',         'condition' => 'Sehat', 'color' => 'Cokelat Putih',    'petGender' => 'B', 'isSteril' => 0, 'petMonth' => 2, 'petYear' => 1, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 115, 'petName' => 'Toby',    'petCategoryId' => 2, 'races' => 'Bulldog',          'condition' => 'Sehat', 'color' => 'Putih Belang',     'petGender' => 'J', 'isSteril' => 1, 'petMonth' => 6, 'petYear' => 4, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 116, 'petName' => 'Lily',    'petCategoryId' => 3, 'races' => 'Siamese',          'condition' => 'Sehat', 'color' => 'Krem Cokelat',     'petGender' => 'B', 'isSteril' => 0, 'petMonth' => 1, 'petYear' => 2, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 117, 'petName' => 'Bruno',   'petCategoryId' => 2, 'races' => 'Rottweiler',       'condition' => 'Sehat', 'color' => 'Hitam Cokelat',    'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 0, 'petYear' => 5, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 118, 'petName' => 'Kucil',   'petCategoryId' => 3, 'races' => 'Domestic',         'condition' => 'Sehat', 'color' => 'Hitam',            'petGender' => 'J', 'isSteril' => 1, 'petMonth' => 4, 'petYear' => 3, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 119, 'petName' => 'Dachi',   'petCategoryId' => 2, 'races' => 'Dachshund',        'condition' => 'Sehat', 'color' => 'Cokelat',          'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 3, 'petYear' => 2, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 120, 'petName' => 'Angel',   'petCategoryId' => 3, 'races' => 'Turkish Angora',   'condition' => 'Sehat', 'color' => 'Putih',            'petGender' => 'B', 'isSteril' => 1, 'petMonth' => 0, 'petYear' => 1, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 121, 'petName' => 'Dino',    'petCategoryId' => 4, 'races' => 'Cockatiel',        'condition' => 'Sehat', 'color' => 'Abu Kuning',       'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 6, 'petYear' => 2, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 122, 'petName' => 'Mela',    'petCategoryId' => 3, 'races' => 'Himalayan',        'condition' => 'Sehat', 'color' => 'Putih Cokelat',    'petGender' => 'B', 'isSteril' => 0, 'petMonth' => 11,'petYear' => 2, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 123, 'petName' => 'Jack',    'petCategoryId' => 2, 'races' => 'Maltese',          'condition' => 'Sehat', 'color' => 'Putih',            'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 2, 'petYear' => 3, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 124, 'petName' => 'Pipit',   'petCategoryId' => 4, 'races' => 'Canary',           'condition' => 'Sehat', 'color' => 'Kuning',           'petGender' => 'B', 'isSteril' => 0, 'petMonth' => 0, 'petYear' => 1, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 125, 'petName' => 'Thor',    'petCategoryId' => 2, 'races' => 'Akita',            'condition' => 'Sehat', 'color' => 'Oranye Putih',     'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 0, 'petYear' => 7, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 126, 'petName' => 'Oreo',    'petCategoryId' => 3, 'races' => 'Domestic',         'condition' => 'Sehat', 'color' => 'Hitam Putih',      'petGender' => 'J', 'isSteril' => 1, 'petMonth' => 7, 'petYear' => 2, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 127, 'petName' => 'Duke',    'petCategoryId' => 2, 'races' => 'Shih Tzu',         'condition' => 'Sehat', 'color' => 'Putih Cokelat',    'petGender' => 'J', 'isSteril' => 0, 'petMonth' => 5, 'petYear' => 4, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 128, 'petName' => 'Cleo',    'petCategoryId' => 3, 'races' => 'Exotic Shorthair', 'condition' => 'Sehat', 'color' => 'Abu-abu',          'petGender' => 'B', 'isSteril' => 1, 'petMonth' => 0, 'petYear' => 3, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 129, 'petName' => 'Bear',    'petCategoryId' => 2, 'races' => 'Chow Chow',        'condition' => 'Sehat', 'color' => 'Merah Kecokelatan','petGender' => 'J', 'isSteril' => 0, 'petMonth' => 3, 'petYear' => 5, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
            ['customerId' => 130, 'petName' => 'Mia',     'petCategoryId' => 6, 'races' => 'Roborovski',       'condition' => 'Sehat', 'color' => 'Putih',            'petGender' => 'B', 'isSteril' => 0, 'petMonth' => 1, 'petYear' => 1, 'createdBy' => 1, 'userUpdateId' => 0, 'isDeleted' => 0, 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('customerPets')->insert($pets);

        $this->command->info('✅  CustomerTableSeeder: 30 customers, 30 telephones, 30 pets inserted.');
    }
}
