<?php

namespace Database\Seeders\Product;

use Illuminate\Database\Seeder;

class ProductClinicCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('productClinicCategories')->delete();
        
        \DB::table('productClinicCategories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'productClinicId' => 1,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            1 => 
            array (
                'id' => 2,
                'productClinicId' => 1,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            2 => 
            array (
                'id' => 3,
                'productClinicId' => 1,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            3 => 
            array (
                'id' => 4,
                'productClinicId' => 2,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            4 => 
            array (
                'id' => 5,
                'productClinicId' => 2,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            5 => 
            array (
                'id' => 6,
                'productClinicId' => 2,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            6 => 
            array (
                'id' => 7,
                'productClinicId' => 3,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            7 => 
            array (
                'id' => 8,
                'productClinicId' => 3,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            8 => 
            array (
                'id' => 9,
                'productClinicId' => 3,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            9 => 
            array (
                'id' => 10,
                'productClinicId' => 4,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            10 => 
            array (
                'id' => 11,
                'productClinicId' => 4,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            11 => 
            array (
                'id' => 12,
                'productClinicId' => 4,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            12 => 
            array (
                'id' => 13,
                'productClinicId' => 5,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            13 => 
            array (
                'id' => 14,
                'productClinicId' => 5,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            14 => 
            array (
                'id' => 15,
                'productClinicId' => 5,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            15 => 
            array (
                'id' => 16,
                'productClinicId' => 6,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            16 => 
            array (
                'id' => 17,
                'productClinicId' => 6,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            17 => 
            array (
                'id' => 18,
                'productClinicId' => 6,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            18 => 
            array (
                'id' => 19,
                'productClinicId' => 7,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            19 => 
            array (
                'id' => 20,
                'productClinicId' => 7,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            20 => 
            array (
                'id' => 21,
                'productClinicId' => 7,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            21 => 
            array (
                'id' => 22,
                'productClinicId' => 8,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            22 => 
            array (
                'id' => 23,
                'productClinicId' => 8,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            23 => 
            array (
                'id' => 24,
                'productClinicId' => 8,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            24 => 
            array (
                'id' => 25,
                'productClinicId' => 9,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            25 => 
            array (
                'id' => 26,
                'productClinicId' => 9,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            26 => 
            array (
                'id' => 27,
                'productClinicId' => 9,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            27 => 
            array (
                'id' => 28,
                'productClinicId' => 10,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            28 => 
            array (
                'id' => 29,
                'productClinicId' => 10,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            29 => 
            array (
                'id' => 30,
                'productClinicId' => 10,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            30 => 
            array (
                'id' => 31,
                'productClinicId' => 11,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            31 => 
            array (
                'id' => 32,
                'productClinicId' => 11,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            32 => 
            array (
                'id' => 33,
                'productClinicId' => 11,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            33 => 
            array (
                'id' => 34,
                'productClinicId' => 12,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            34 => 
            array (
                'id' => 35,
                'productClinicId' => 12,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            35 => 
            array (
                'id' => 36,
                'productClinicId' => 12,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            36 => 
            array (
                'id' => 37,
                'productClinicId' => 13,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            37 => 
            array (
                'id' => 38,
                'productClinicId' => 13,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            38 => 
            array (
                'id' => 39,
                'productClinicId' => 13,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            39 => 
            array (
                'id' => 40,
                'productClinicId' => 14,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            40 => 
            array (
                'id' => 41,
                'productClinicId' => 14,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            41 => 
            array (
                'id' => 42,
                'productClinicId' => 14,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            42 => 
            array (
                'id' => 43,
                'productClinicId' => 15,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            43 => 
            array (
                'id' => 44,
                'productClinicId' => 15,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            44 => 
            array (
                'id' => 45,
                'productClinicId' => 15,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            45 => 
            array (
                'id' => 46,
                'productClinicId' => 16,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            46 => 
            array (
                'id' => 47,
                'productClinicId' => 16,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            47 => 
            array (
                'id' => 48,
                'productClinicId' => 16,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            48 => 
            array (
                'id' => 49,
                'productClinicId' => 17,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            49 => 
            array (
                'id' => 50,
                'productClinicId' => 17,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            50 => 
            array (
                'id' => 51,
                'productClinicId' => 17,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            51 => 
            array (
                'id' => 52,
                'productClinicId' => 18,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            52 => 
            array (
                'id' => 53,
                'productClinicId' => 18,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            53 => 
            array (
                'id' => 54,
                'productClinicId' => 18,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            54 => 
            array (
                'id' => 55,
                'productClinicId' => 19,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            55 => 
            array (
                'id' => 56,
                'productClinicId' => 19,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            56 => 
            array (
                'id' => 57,
                'productClinicId' => 19,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            57 => 
            array (
                'id' => 58,
                'productClinicId' => 20,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            58 => 
            array (
                'id' => 59,
                'productClinicId' => 20,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            59 => 
            array (
                'id' => 60,
                'productClinicId' => 20,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            60 => 
            array (
                'id' => 61,
                'productClinicId' => 21,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            61 => 
            array (
                'id' => 62,
                'productClinicId' => 21,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            62 => 
            array (
                'id' => 63,
                'productClinicId' => 21,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            63 => 
            array (
                'id' => 64,
                'productClinicId' => 22,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            64 => 
            array (
                'id' => 65,
                'productClinicId' => 22,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            65 => 
            array (
                'id' => 66,
                'productClinicId' => 22,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            66 => 
            array (
                'id' => 67,
                'productClinicId' => 23,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            67 => 
            array (
                'id' => 68,
                'productClinicId' => 23,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            68 => 
            array (
                'id' => 69,
                'productClinicId' => 23,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            69 => 
            array (
                'id' => 70,
                'productClinicId' => 24,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            70 => 
            array (
                'id' => 71,
                'productClinicId' => 24,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            71 => 
            array (
                'id' => 72,
                'productClinicId' => 24,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            72 => 
            array (
                'id' => 73,
                'productClinicId' => 25,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            73 => 
            array (
                'id' => 74,
                'productClinicId' => 25,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            74 => 
            array (
                'id' => 75,
                'productClinicId' => 25,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            75 => 
            array (
                'id' => 76,
                'productClinicId' => 26,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            76 => 
            array (
                'id' => 77,
                'productClinicId' => 26,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            77 => 
            array (
                'id' => 78,
                'productClinicId' => 26,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            78 => 
            array (
                'id' => 79,
                'productClinicId' => 27,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            79 => 
            array (
                'id' => 80,
                'productClinicId' => 27,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            80 => 
            array (
                'id' => 81,
                'productClinicId' => 27,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            81 => 
            array (
                'id' => 82,
                'productClinicId' => 28,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            82 => 
            array (
                'id' => 83,
                'productClinicId' => 28,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            83 => 
            array (
                'id' => 84,
                'productClinicId' => 28,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            84 => 
            array (
                'id' => 85,
                'productClinicId' => 29,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            85 => 
            array (
                'id' => 86,
                'productClinicId' => 29,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            86 => 
            array (
                'id' => 87,
                'productClinicId' => 29,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            87 => 
            array (
                'id' => 88,
                'productClinicId' => 30,
                'productCategoryId' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            88 => 
            array (
                'id' => 89,
                'productClinicId' => 30,
                'productCategoryId' => 2,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            89 => 
            array (
                'id' => 90,
                'productClinicId' => 30,
                'productCategoryId' => 3,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
        ));
        
        
    }
}