<?php

namespace Database\Seeders\Product;

use Illuminate\Database\Seeder;

class ProductClinicQuantitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('productClinicQuantities')->delete();
        
        \DB::table('productClinicQuantities')->insert(array (
            0 => 
            array (
                'id' => 1,
                'productClinicId' => 1,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            1 => 
            array (
                'id' => 2,
                'productClinicId' => 1,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            2 => 
            array (
                'id' => 3,
                'productClinicId' => 2,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            3 => 
            array (
                'id' => 4,
                'productClinicId' => 2,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            4 => 
            array (
                'id' => 5,
                'productClinicId' => 3,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            5 => 
            array (
                'id' => 6,
                'productClinicId' => 3,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            6 => 
            array (
                'id' => 7,
                'productClinicId' => 4,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            7 => 
            array (
                'id' => 8,
                'productClinicId' => 4,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            8 => 
            array (
                'id' => 9,
                'productClinicId' => 5,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            9 => 
            array (
                'id' => 10,
                'productClinicId' => 5,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            10 => 
            array (
                'id' => 11,
                'productClinicId' => 6,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            11 => 
            array (
                'id' => 12,
                'productClinicId' => 6,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            12 => 
            array (
                'id' => 13,
                'productClinicId' => 7,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            13 => 
            array (
                'id' => 14,
                'productClinicId' => 7,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            14 => 
            array (
                'id' => 15,
                'productClinicId' => 8,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            15 => 
            array (
                'id' => 16,
                'productClinicId' => 8,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            16 => 
            array (
                'id' => 17,
                'productClinicId' => 9,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            17 => 
            array (
                'id' => 18,
                'productClinicId' => 9,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            18 => 
            array (
                'id' => 19,
                'productClinicId' => 10,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            19 => 
            array (
                'id' => 20,
                'productClinicId' => 10,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            20 => 
            array (
                'id' => 21,
                'productClinicId' => 11,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            21 => 
            array (
                'id' => 22,
                'productClinicId' => 11,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            22 => 
            array (
                'id' => 23,
                'productClinicId' => 12,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            23 => 
            array (
                'id' => 24,
                'productClinicId' => 12,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            24 => 
            array (
                'id' => 25,
                'productClinicId' => 13,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            25 => 
            array (
                'id' => 26,
                'productClinicId' => 13,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            26 => 
            array (
                'id' => 27,
                'productClinicId' => 14,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            27 => 
            array (
                'id' => 28,
                'productClinicId' => 14,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            28 => 
            array (
                'id' => 29,
                'productClinicId' => 15,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            29 => 
            array (
                'id' => 30,
                'productClinicId' => 15,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            30 => 
            array (
                'id' => 31,
                'productClinicId' => 16,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            31 => 
            array (
                'id' => 32,
                'productClinicId' => 16,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            32 => 
            array (
                'id' => 33,
                'productClinicId' => 17,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            33 => 
            array (
                'id' => 34,
                'productClinicId' => 17,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            34 => 
            array (
                'id' => 35,
                'productClinicId' => 18,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            35 => 
            array (
                'id' => 36,
                'productClinicId' => 18,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            36 => 
            array (
                'id' => 37,
                'productClinicId' => 28,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            37 => 
            array (
                'id' => 38,
                'productClinicId' => 28,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            38 => 
            array (
                'id' => 39,
                'productClinicId' => 29,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            39 => 
            array (
                'id' => 40,
                'productClinicId' => 29,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            40 => 
            array (
                'id' => 41,
                'productClinicId' => 30,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            41 => 
            array (
                'id' => 42,
                'productClinicId' => 30,
                'fromQty' => 1,
                'toQty' => 3,
                'price' => '25000.00',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
        ));
        
        
    }
}