<?php

namespace Database\Seeders\Product;

use Illuminate\Database\Seeder;

class ProductSellRemindersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('productSellReminders')->delete();
        
        \DB::table('productSellReminders')->insert(array (
            0 => 
            array (
                'id' => 1,
                'productSellId' => 1,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:50',
                'updated_at' => '2023-01-15 14:20:50',
            ),
            1 => 
            array (
                'id' => 2,
                'productSellId' => 1,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:50',
                'updated_at' => '2023-01-15 14:20:50',
            ),
            2 => 
            array (
                'id' => 3,
                'productSellId' => 2,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:50',
                'updated_at' => '2023-01-15 14:20:50',
            ),
            3 => 
            array (
                'id' => 4,
                'productSellId' => 2,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:50',
                'updated_at' => '2023-01-15 14:20:50',
            ),
            4 => 
            array (
                'id' => 5,
                'productSellId' => 3,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:50',
                'updated_at' => '2023-01-15 14:20:50',
            ),
            5 => 
            array (
                'id' => 6,
                'productSellId' => 3,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:50',
                'updated_at' => '2023-01-15 14:20:50',
            ),
            6 => 
            array (
                'id' => 7,
                'productSellId' => 4,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:52',
                'updated_at' => '2023-01-15 14:20:52',
            ),
            7 => 
            array (
                'id' => 8,
                'productSellId' => 4,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:52',
                'updated_at' => '2023-01-15 14:20:52',
            ),
            8 => 
            array (
                'id' => 9,
                'productSellId' => 5,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:52',
                'updated_at' => '2023-01-15 14:20:52',
            ),
            9 => 
            array (
                'id' => 10,
                'productSellId' => 5,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:52',
                'updated_at' => '2023-01-15 14:20:52',
            ),
            10 => 
            array (
                'id' => 11,
                'productSellId' => 6,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:52',
                'updated_at' => '2023-01-15 14:20:52',
            ),
            11 => 
            array (
                'id' => 12,
                'productSellId' => 6,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:52',
                'updated_at' => '2023-01-15 14:20:52',
            ),
            12 => 
            array (
                'id' => 13,
                'productSellId' => 7,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:55',
                'updated_at' => '2023-01-15 14:20:55',
            ),
            13 => 
            array (
                'id' => 14,
                'productSellId' => 7,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:55',
                'updated_at' => '2023-01-15 14:20:55',
            ),
            14 => 
            array (
                'id' => 15,
                'productSellId' => 8,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:55',
                'updated_at' => '2023-01-15 14:20:55',
            ),
            15 => 
            array (
                'id' => 16,
                'productSellId' => 8,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:55',
                'updated_at' => '2023-01-15 14:20:55',
            ),
            16 => 
            array (
                'id' => 17,
                'productSellId' => 9,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:55',
                'updated_at' => '2023-01-15 14:20:55',
            ),
            17 => 
            array (
                'id' => 18,
                'productSellId' => 9,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:55',
                'updated_at' => '2023-01-15 14:20:55',
            ),
            18 => 
            array (
                'id' => 19,
                'productSellId' => 10,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:54:58',
                'updated_at' => '2023-01-19 00:54:58',
            ),
            19 => 
            array (
                'id' => 20,
                'productSellId' => 10,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:54:58',
                'updated_at' => '2023-01-19 00:54:58',
            ),
            20 => 
            array (
                'id' => 21,
                'productSellId' => 11,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:54:58',
                'updated_at' => '2023-01-19 00:54:58',
            ),
            21 => 
            array (
                'id' => 22,
                'productSellId' => 11,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:54:58',
                'updated_at' => '2023-01-19 00:54:58',
            ),
            22 => 
            array (
                'id' => 23,
                'productSellId' => 12,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:54:58',
                'updated_at' => '2023-01-19 00:54:58',
            ),
            23 => 
            array (
                'id' => 24,
                'productSellId' => 12,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:54:58',
                'updated_at' => '2023-01-19 00:54:58',
            ),
            24 => 
            array (
                'id' => 25,
                'productSellId' => 13,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:27',
                'updated_at' => '2023-01-19 00:55:27',
            ),
            25 => 
            array (
                'id' => 26,
                'productSellId' => 13,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:27',
                'updated_at' => '2023-01-19 00:55:27',
            ),
            26 => 
            array (
                'id' => 27,
                'productSellId' => 14,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:27',
                'updated_at' => '2023-01-19 00:55:27',
            ),
            27 => 
            array (
                'id' => 28,
                'productSellId' => 14,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:27',
                'updated_at' => '2023-01-19 00:55:27',
            ),
            28 => 
            array (
                'id' => 29,
                'productSellId' => 15,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:27',
                'updated_at' => '2023-01-19 00:55:27',
            ),
            29 => 
            array (
                'id' => 30,
                'productSellId' => 15,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:27',
                'updated_at' => '2023-01-19 00:55:27',
            ),
            30 => 
            array (
                'id' => 31,
                'productSellId' => 16,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:47',
                'updated_at' => '2023-01-19 00:55:47',
            ),
            31 => 
            array (
                'id' => 32,
                'productSellId' => 16,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:47',
                'updated_at' => '2023-01-19 00:55:47',
            ),
            32 => 
            array (
                'id' => 33,
                'productSellId' => 17,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:47',
                'updated_at' => '2023-01-19 00:55:47',
            ),
            33 => 
            array (
                'id' => 34,
                'productSellId' => 17,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:47',
                'updated_at' => '2023-01-19 00:55:47',
            ),
            34 => 
            array (
                'id' => 35,
                'productSellId' => 18,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:47',
                'updated_at' => '2023-01-19 00:55:47',
            ),
            35 => 
            array (
                'id' => 36,
                'productSellId' => 18,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:55:47',
                'updated_at' => '2023-01-19 00:55:47',
            ),
            36 => 
            array (
                'id' => 37,
                'productSellId' => 19,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:56:17',
                'updated_at' => '2023-01-19 00:56:17',
            ),
            37 => 
            array (
                'id' => 38,
                'productSellId' => 19,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:56:17',
                'updated_at' => '2023-01-19 00:56:17',
            ),
            38 => 
            array (
                'id' => 39,
                'productSellId' => 20,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:56:17',
                'updated_at' => '2023-01-19 00:56:17',
            ),
            39 => 
            array (
                'id' => 40,
                'productSellId' => 20,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:56:17',
                'updated_at' => '2023-01-19 00:56:17',
            ),
            40 => 
            array (
                'id' => 41,
                'productSellId' => 21,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:56:17',
                'updated_at' => '2023-01-19 00:56:17',
            ),
            41 => 
            array (
                'id' => 42,
                'productSellId' => 21,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:56:17',
                'updated_at' => '2023-01-19 00:56:17',
            ),
        ));
        
        
    }
}