<?php

namespace Database\Seeders\Product;

use Illuminate\Database\Seeder;

class ProductInventoryListsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('productInventoryLists')->delete();
        
        \DB::table('productInventoryLists')->insert(array (
            0 => 
            array (
                'id' => 1,
                'productInventoryId' => 1,
                'productType' => 'productClinic',
                'productId' => 1,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 1,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => 3,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => '2023-01-15 23:35:04',
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-10-20',
                'isAnyImage' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 23:20:05',
                'updated_at' => '2023-01-15 23:35:04',
            ),
            1 => 
            array (
                'id' => 2,
                'productInventoryId' => 1,
                'productType' => 'productClinic',
                'productId' => 4,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-10-20',
                'isAnyImage' => 0,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 23:20:05',
                'updated_at' => '2023-01-15 23:20:05',
            ),
            2 => 
            array (
                'id' => 3,
                'productInventoryId' => 1,
                'productType' => 'productClinic',
                'productId' => 7,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-12-30',
                'isAnyImage' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 23:20:05',
                'updated_at' => '2023-01-15 23:20:05',
            ),
            3 => 
            array (
                'id' => 4,
                'productInventoryId' => 2,
                'productType' => 'productClinic',
                'productId' => 1,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-10-20',
                'isAnyImage' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 23:20:15',
                'updated_at' => '2023-01-15 23:20:15',
            ),
            4 => 
            array (
                'id' => 5,
                'productInventoryId' => 2,
                'productType' => 'productClinic',
                'productId' => 4,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-10-20',
                'isAnyImage' => 0,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 23:20:15',
                'updated_at' => '2023-01-15 23:20:15',
            ),
            5 => 
            array (
                'id' => 6,
                'productInventoryId' => 2,
                'productType' => 'productClinic',
                'productId' => 7,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-12-30',
                'isAnyImage' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 23:20:15',
                'updated_at' => '2023-01-15 23:20:15',
            ),
            6 => 
            array (
                'id' => 7,
                'productInventoryId' => 3,
                'productType' => 'productClinic',
                'productId' => 1,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-10-20',
                'isAnyImage' => 1,
                'isDeleted' => 0,
                'userId' => 3,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-16 01:52:00',
                'updated_at' => '2023-01-16 01:52:00',
            ),
            7 => 
            array (
                'id' => 8,
                'productInventoryId' => 3,
                'productType' => 'productClinic',
                'productId' => 4,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-10-20',
                'isAnyImage' => 0,
                'isDeleted' => 0,
                'userId' => 3,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-16 01:52:00',
                'updated_at' => '2023-01-16 01:52:00',
            ),
            8 => 
            array (
                'id' => 9,
                'productInventoryId' => 3,
                'productType' => 'productClinic',
                'productId' => 7,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-12-30',
                'isAnyImage' => 1,
                'isDeleted' => 0,
                'userId' => 3,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-16 01:52:00',
                'updated_at' => '2023-01-16 01:52:00',
            ),
            9 => 
            array (
                'id' => 17,
                'productInventoryId' => 9,
                'productType' => 'productClinic',
                'productId' => 1,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-10-20',
                'isAnyImage' => 0,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 01:00:29',
                'updated_at' => '2023-01-19 01:00:29',
            ),
            10 => 
            array (
                'id' => 18,
                'productInventoryId' => 9,
                'productType' => 'productClinic',
                'productId' => 4,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-10-20',
                'isAnyImage' => 0,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 01:00:29',
                'updated_at' => '2023-01-19 01:00:29',
            ),
            11 => 
            array (
                'id' => 19,
                'productInventoryId' => 9,
                'productType' => 'productClinic',
                'productId' => 7,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-12-30',
                'isAnyImage' => 1,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 01:00:29',
                'updated_at' => '2023-01-19 01:00:29',
            ),
            12 => 
            array (
                'id' => 20,
                'productInventoryId' => 10,
                'productType' => 'productClinic',
                'productId' => 1,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-10-20',
                'isAnyImage' => 0,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 01:00:41',
                'updated_at' => '2023-01-19 01:00:41',
            ),
            13 => 
            array (
                'id' => 21,
                'productInventoryId' => 10,
                'productType' => 'productClinic',
                'productId' => 4,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-10-20',
                'isAnyImage' => 0,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 01:00:41',
                'updated_at' => '2023-01-19 01:00:41',
            ),
            14 => 
            array (
                'id' => 22,
                'productInventoryId' => 10,
                'productType' => 'productClinic',
                'productId' => 7,
                'usageId' => 1,
                'quantity' => 2,
                'isApprovedOffice' => 0,
                'isApprovedAdmin' => 0,
                'userApproveOfficeId' => NULL,
                'userApproveAdminId' => NULL,
                'userApproveOfficeAt' => NULL,
                'userApproveAdminAt' => NULL,
                'reasonOffice' => NULL,
                'reasonAdmin' => NULL,
                'itemCondition' => 'bagus',
                'dateCondition' => '2022-12-30',
                'isAnyImage' => 0,
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 01:00:41',
                'updated_at' => '2023-01-19 01:00:41',
            ),
        ));
        
        
    }
}