<?php

namespace Database\Seeders\Product;

use Illuminate\Database\Seeder;

class ProductClinicRemindersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('productClinicReminders')->delete();
        
        \DB::table('productClinicReminders')->insert(array (
            0 => 
            array (
                'id' => 1,
                'productClinicId' => 1,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            1 => 
            array (
                'id' => 2,
                'productClinicId' => 1,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            2 => 
            array (
                'id' => 3,
                'productClinicId' => 2,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            3 => 
            array (
                'id' => 4,
                'productClinicId' => 2,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            4 => 
            array (
                'id' => 5,
                'productClinicId' => 3,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            5 => 
            array (
                'id' => 6,
                'productClinicId' => 3,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:44',
                'updated_at' => '2023-01-14 22:55:44',
            ),
            6 => 
            array (
                'id' => 7,
                'productClinicId' => 4,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            7 => 
            array (
                'id' => 8,
                'productClinicId' => 4,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            8 => 
            array (
                'id' => 9,
                'productClinicId' => 5,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            9 => 
            array (
                'id' => 10,
                'productClinicId' => 5,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            10 => 
            array (
                'id' => 11,
                'productClinicId' => 6,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            11 => 
            array (
                'id' => 12,
                'productClinicId' => 6,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:55:54',
                'updated_at' => '2023-01-14 22:55:54',
            ),
            12 => 
            array (
                'id' => 13,
                'productClinicId' => 7,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            13 => 
            array (
                'id' => 14,
                'productClinicId' => 7,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            14 => 
            array (
                'id' => 15,
                'productClinicId' => 8,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            15 => 
            array (
                'id' => 16,
                'productClinicId' => 8,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            16 => 
            array (
                'id' => 17,
                'productClinicId' => 9,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            17 => 
            array (
                'id' => 18,
                'productClinicId' => 9,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-14 22:57:01',
                'updated_at' => '2023-01-14 22:57:01',
            ),
            18 => 
            array (
                'id' => 19,
                'productClinicId' => 10,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            19 => 
            array (
                'id' => 20,
                'productClinicId' => 10,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            20 => 
            array (
                'id' => 21,
                'productClinicId' => 11,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            21 => 
            array (
                'id' => 22,
                'productClinicId' => 11,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            22 => 
            array (
                'id' => 23,
                'productClinicId' => 12,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            23 => 
            array (
                'id' => 24,
                'productClinicId' => 12,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:38',
                'updated_at' => '2023-01-15 14:20:38',
            ),
            24 => 
            array (
                'id' => 25,
                'productClinicId' => 13,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            25 => 
            array (
                'id' => 26,
                'productClinicId' => 13,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            26 => 
            array (
                'id' => 27,
                'productClinicId' => 14,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            27 => 
            array (
                'id' => 28,
                'productClinicId' => 14,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            28 => 
            array (
                'id' => 29,
                'productClinicId' => 15,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            29 => 
            array (
                'id' => 30,
                'productClinicId' => 15,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:41',
                'updated_at' => '2023-01-15 14:20:41',
            ),
            30 => 
            array (
                'id' => 31,
                'productClinicId' => 16,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            31 => 
            array (
                'id' => 32,
                'productClinicId' => 16,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            32 => 
            array (
                'id' => 33,
                'productClinicId' => 17,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            33 => 
            array (
                'id' => 34,
                'productClinicId' => 17,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            34 => 
            array (
                'id' => 35,
                'productClinicId' => 18,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            35 => 
            array (
                'id' => 36,
                'productClinicId' => 18,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-15 14:20:46',
                'updated_at' => '2023-01-15 14:20:46',
            ),
            36 => 
            array (
                'id' => 37,
                'productClinicId' => 19,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            37 => 
            array (
                'id' => 38,
                'productClinicId' => 19,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            38 => 
            array (
                'id' => 39,
                'productClinicId' => 20,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            39 => 
            array (
                'id' => 40,
                'productClinicId' => 20,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            40 => 
            array (
                'id' => 41,
                'productClinicId' => 21,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            41 => 
            array (
                'id' => 42,
                'productClinicId' => 21,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:07',
                'updated_at' => '2023-01-19 00:58:07',
            ),
            42 => 
            array (
                'id' => 43,
                'productClinicId' => 22,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            43 => 
            array (
                'id' => 44,
                'productClinicId' => 22,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            44 => 
            array (
                'id' => 45,
                'productClinicId' => 23,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            45 => 
            array (
                'id' => 46,
                'productClinicId' => 23,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            46 => 
            array (
                'id' => 47,
                'productClinicId' => 24,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            47 => 
            array (
                'id' => 48,
                'productClinicId' => 24,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:58:42',
                'updated_at' => '2023-01-19 00:58:42',
            ),
            48 => 
            array (
                'id' => 49,
                'productClinicId' => 25,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            49 => 
            array (
                'id' => 50,
                'productClinicId' => 25,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            50 => 
            array (
                'id' => 51,
                'productClinicId' => 26,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            51 => 
            array (
                'id' => 52,
                'productClinicId' => 26,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            52 => 
            array (
                'id' => 53,
                'productClinicId' => 27,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            53 => 
            array (
                'id' => 54,
                'productClinicId' => 27,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:00',
                'updated_at' => '2023-01-19 00:59:00',
            ),
            54 => 
            array (
                'id' => 55,
                'productClinicId' => 28,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            55 => 
            array (
                'id' => 56,
                'productClinicId' => 28,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            56 => 
            array (
                'id' => 57,
                'productClinicId' => 29,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            57 => 
            array (
                'id' => 58,
                'productClinicId' => 29,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            58 => 
            array (
                'id' => 59,
                'productClinicId' => 30,
                'unit' => 1,
                'timing' => 'Days',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
            59 => 
            array (
                'id' => 60,
                'productClinicId' => 30,
                'unit' => 5,
                'timing' => 'Hours',
                'status' => 'After Add On',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => '2023-01-19 00:59:12',
                'updated_at' => '2023-01-19 00:59:12',
            ),
        ));
        
        
    }
}