<?php

namespace Database\Seeders\Menu;

use Illuminate\Database\Seeder;

class GrandChildrenMenuGroupsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('grandChildrenMenuGroups')->delete();

        \DB::table('grandChildrenMenuGroups')->insert(array (
            0 =>
            array (
                'id' => 1,
                'childrenId' => 4,
                'identify' => 'customer-dashboard',
                'title' => 'Dashboard',
                'type' => 'item',
                'url' => '/customer/dashboard',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'childrenId' => 4,
                'identify' => 'customer-list',
                'title' => 'customer-list',
                'type' => 'item',
                'url' => '/customer/list',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'childrenId' => 4,
                'identify' => 'customer-template',
                'title' => 'Template',
                'type' => 'item',
                'url' => '/customer/template',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'childrenId' => 4,
                'identify' => 'customer-merge',
                'title' => 'merge',
                'type' => 'item',
                'url' => '/customer/merge',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'childrenId' => 4,
                'identify' => 'customer-static-data',
                'title' => 'static-data',
                'type' => 'item',
                'url' => '/customer/static-data',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'childrenId' => 4,
                'identify' => 'customer-import',
                'title' => 'import',
                'type' => 'item',
                'url' => '/customer/import',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 10,
                'childrenId' => 5,
                'identify' => 'staff-list',
                'title' => 'staff-list',
                'type' => 'item',
                'url' => '/staff/list',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 11,
                'childrenId' => 5,
                'identify' => 'staff-leave-approval',
                'title' => 'leave-approval',
                'type' => 'item',
                'url' => '/staff/leave-approval',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 12,
                'childrenId' => 5,
                'identify' => 'staff-access-control',
                'title' => 'access-control',
                'type' => 'item',
                'url' => '/staff/access-control',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 13,
                'childrenId' => 5,
                'identify' => 'staff-security-group',
                'title' => 'security-group',
                'type' => 'item',
                'url' => '/staff/security-group',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'id' => 14,
                'childrenId' => 5,
                'identify' => 'staff-schedule',
                'title' => 'schedule',
                'type' => 'item',
                'url' => '/staff/schedule',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 =>
            array (
                'id' => 15,
                'childrenId' => 5,
                'identify' => 'staff-static-data',
                'title' => 'static-data',
                'type' => 'item',
                'url' => '/staff/static-data',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 =>
            array (
                'id' => 16,
                'childrenId' => 6,
                'identify' => 'promotion-dashboard',
                'title' => 'Dashboard',
                'type' => 'item',
                'url' => '/promotion/dashboard',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'id' => 17,
                'childrenId' => 6,
                'identify' => 'promotion-discount',
                'title' => 'discount',
                'type' => 'item',
                'url' => '/promotion/discount',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 =>
            array (
                'id' => 18,
                'childrenId' => 6,
                'identify' => 'promotion-partner',
                'title' => 'partner',
                'type' => 'item',
                'url' => '/promotion/partner',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 =>
            array (
                'id' => 19,
                'childrenId' => 7,
                'identify' => 'service-dashboard',
                'title' => 'Dashboard',
                'type' => 'item',
                'url' => '/service/dashboard',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 =>
            array (
                'id' => 20,
                'childrenId' => 7,
                'identify' => 'service-list',
                'title' => 'service-list',
                'type' => 'item',
                'url' => '/service/list',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 =>
            array (
                'id' => 21,
                'childrenId' => 7,
                'identify' => 'service-treatment-plan',
                'title' => 'treatment-plan',
                'type' => 'item',
                'url' => '/service/treatment',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 =>
            array (
                'id' => 22,
                'childrenId' => 7,
                'identify' => 'service-category',
                'title' => 'category',
                'type' => 'item',
                'url' => '/service/category',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 =>
            array (
                'id' => 23,
                'childrenId' => 7,
                'identify' => 'service-policies',
                'title' => 'policies',
                'type' => 'item',
                'url' => '/service/policies',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 =>
            array (
                'id' => 24,
                'childrenId' => 7,
                'identify' => 'service-template',
                'title' => 'Template',
                'type' => 'item',
                'url' => '/service/template',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 =>
            array (
                'id' => 25,
                'childrenId' => 7,
                'identify' => 'service-static-data',
                'title' => 'static-data',
                'type' => 'item',
                'url' => '/service/static-data',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 =>
            array (
                'id' => 26,
                'childrenId' => 7,
                'identify' => 'service-import',
                'title' => 'import',
                'type' => 'item',
                'url' => '/service/import',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 =>
            array (
                'id' => 27,
                'childrenId' => 8,
                'identify' => 'product-dashboard',
                'title' => 'Dashboard',
                'type' => 'item',
                'url' => '/product/dashboard',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 =>
            array (
                'id' => 28,
                'childrenId' => 8,
                'identify' => 'product-list',
                'title' => 'product-list',
                'type' => 'item',
                'url' => '/product/product-list',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 =>
            array (
                'id' => 29,
                'childrenId' => 8,
                'identify' => 'product-bundle',
                'title' => 'bundle',
                'type' => 'item',
                'url' => '/product/bundle',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 =>
            array (
                'id' => 30,
                'childrenId' => 8,
                'identify' => 'product-category',
                'title' => 'category',
                'type' => 'item',
                'url' => '/product/category',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 =>
            array (
                'id' => 31,
                'childrenId' => 8,
                'identify' => 'product-policies',
                'title' => 'policies',
                'type' => 'item',
                'url' => '/product/policies',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 =>
            array (
                'id' => 32,
                'childrenId' => 8,
                'identify' => 'product-restock',
                'title' => 'restock',
                'type' => 'item',
                'url' => '/product/restock',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 =>
            array (
                'id' => 33,
                'childrenId' => 8,
                'identify' => 'product-transfer',
                'title' => 'transfer',
                'type' => 'item',
                'url' => '/product/transfer',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 =>
            array (
                'id' => 34,
                'childrenId' => 8,
                'identify' => 'product-delivery-agent',
                'title' => 'delivery-agent',
                'type' => 'item',
                'url' => '/product/delivery-agent',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 =>
            array (
                'id' => 35,
                'childrenId' => 8,
                'identify' => 'product-static-data',
                'title' => 'static-data',
                'type' => 'item',
                'url' => '/product/static-data',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 =>
            array (
                'id' => 36,
                'childrenId' => 9,
                'identify' => 'location-list',
                'title' => 'location-list',
                'type' => 'item',
                'url' => '/location/location-list',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 =>
            array (
                'id' => 37,
                'childrenId' => 9,
                'identify' => 'location-facilities',
                'title' => 'location-facilities',
                'type' => 'item',
                'url' => '/location/location-facilities',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 =>
            array (
                'id' => 38,
                'childrenId' => 9,
                'identify' => 'location-static-data',
                'title' => 'static-data',
                'type' => 'item',
                'url' => '/location/static-data',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 =>
            array (
                'id' => 39,
                'childrenId' => 10,
                'identify' => 'finance-dashboard',
                'title' => 'Dashboard',
                'type' => 'item',
                'url' => '/finance/dashboard',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 =>
            array (
                'id' => 40,
                'childrenId' => 10,
                'identify' => 'finance-sales',
                'title' => 'sales',
                'type' => 'item',
                'url' => '/finance/finance-sales',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 =>
            array (
                'id' => 41,
                'childrenId' => 10,
                'identify' => 'finance-quotation',
                'title' => 'quotation',
                'type' => 'item',
                'url' => '/finance/quotation',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 =>
            array (
                'id' => 42,
                'childrenId' => 10,
                'identify' => 'finance-expenses',
                'title' => 'expenses',
                'type' => 'item',
                'url' => '/finance/expenses',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 =>
            array (
                'id' => 43,
                'childrenId' => 10,
                'identify' => 'finance-static-data',
                'title' => 'static-data',
                'type' => 'item',
                'url' => '/finance/static-data',
                'isDeleted' => 0,
                'userId' => 1,
                'userUpdateId' => NULL,
                'deletedBy' => NULL,
                'deletedAt' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));


    }
}
